### PR TITLE
proofreading of readme

### PR DESCRIPTION
**Pull request by strawberry-choco**
Basic proofreading till paragraph `Prepare the image`.

### CODE REVIEW

**Comment by htruong** [comment]
Thank you, I am not a native speaker, so this helps a lot!

**Comment by strawberry-choco** [comment]
No problem. :)

**Comment by htruong** [comment]
Please feel free to proofread the whole thing, and please let me know how can I address your name so I can credit you accordingly :)

**Comment by strawberry-choco** [comment]
I am proofreading the rest now. You can simply call me `chrunchyjesus` (crunchy is misstyped on purpose). Being credited might be a bit too much of an honour for what I have done but thanks!

**Pull request merged**
